### ISSUE TITLE
Use of brackets and "æøå"

### ISSUE THREAD

**Issue by Zenjjim** [jaywcjlove/hotkeys-js#207]
I am creating a project in Norwegian, and wish to add "alt + å" as a hotkey. When i use useHotkeys('*', (e) => console.log(e)); i can see that it is listening to the keypress å and I get an output. However if I use the same hook with useHotkeys('å', (e) => console.log(foo)), i get no output.

The norwegian "å" is equivalent to "{" in the standard keybord config

**Comment by jaywcjlove** [comment]
@Zenjjim I don't know how to test it, welcome to submit PR.
