### ISSUE TITLE
Demo URL not working (404)

### ISSUE THREAD

**Issue by bluefirex** [jaywcjlove/hotkeys-js#430]
Trying out the demo page linked to from the README leads to a 404: https://wangchujiang.com/hotkeys/

![grafik](https://github.com/jaywcjlove/hotkeys-js/assets/357398/ae9ca08d-6b33-46dd-bf15-6437a4d3354c)

**Comment by jaywcjlove** [comment]
@bluefirex i fixed it, thx!
