### ISSUE TITLE
command+shift+] doesn't work on mac

### ISSUE THREAD

**Issue by denis-mnml** [jaywcjlove/hotkeys-js#435]
Hi there :)

"command+shift+]" and "command+shift+[" doesn't work on mac. Tested in chrome and safari.
"ctrl+shift+]" and "ctrl+shift+[" work well.

You can try this [https://wangchujiang.com/hotkeys-js/](https://wangchujiang.com/hotkeys-js/)

**Comment by jaywcjlove** [comment]
https://codepen.io/jaywcjlove/pen/gOQGxOO?editors=0010

@denis-mnml I tested it and it conflicts with browser shortcuts. Currently I don't know of any good solution.

**Comment by denis-mnml** [comment]
@jaywcjlove It is a pity that this cannot be circumvented using e.preventDefault() or e.stopPropagation(). I hope there will be an opportunity to get around this soon.
