### ISSUE TITLE
怎么监听同时按下的键？我想录制快捷键。

### ISSUE THREAD

**Issue by Jarvie789** [jaywcjlove/hotkeys-js#436]
如题

**Comment by jaywcjlove** [comment]
<img width="646" alt="image" src="https://github.com/jaywcjlove/hotkeys-js/assets/1680273/056dceca-9777-4207-8809-e0052f67d522">

@Jarvie789   回调函数返回一个记录，可以使用 `hotkeysEvent.keys`, 需要更新到 `v3.11.0`,

```js
hotkeys('*', (evn, hotkeysEvent) => {
  console.log('heven', hotkeysEvent);
  console.log('keys', hotkeysEvent.keys);
})
```

**Comment by Jarvie789** [comment]
感谢老哥！

**Comment by Jarvie789** [comment]
> <img alt="image" width="646" src="https://user-images.githubusercontent.com/1680273/252141629-056dceca-9777-4207-8809-e0052f67d522.png">
> @Jarvie789 回调函数返回一个记录，可以使用 `hotkeysEvent.keys`, 需要更新到 `v3.11.0`,
> 
> ```js
> hotkeys('*', (evn, hotkeysEvent) => {
>   console.log('heven', hotkeysEvent);
>   console.log('keys', hotkeysEvent.keys);
> })
> ```
感谢老哥！
