### ISSUE TITLE
unbind is broken

### ISSUE THREAD

**Issue by kuechlerm** [jaywcjlove/hotkeys-js#470]
Please check this REPL: https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE22PQWvDMAyF_4rRxQlk7T1NAzsUBjts0O4w5jFSx-m8OpKx5UEJ-e8jJGy0TCe9p4_H0wCddSZC-TYANr2BEu69hwL44icRv41jAwVESkFPThV1sJ5rhYpt7ymw-CQ-m0sUXaBeyEXdfUW5UThhXULNllBEw8l_LECWD9NRsSaM5MzK0SmTV4jMNzOy6FXCo8U2u7Ez2chCZLnY1mLJvElt_pnf8HFeRoXV-u85rI6JmVAQltpZfd4OV93Ger87vDyLh6fD4-51X61nvIYCemptZ00LJYdkxvfxB_T8gARmAQAA

- click the button on the right "SETUP HOTKEYS" more than once
- press "a" on the keyboard
- see on the console of the REPL (bottom right) that the handler for "a" fires more than once

**Comment by jaywcjlove** [comment]
@kuechlerm Upgrade `v3.13.5`

**Comment by kuechlerm** [comment]
That works, thank you!
