### ISSUE TITLE
Problem with f11

### ISSUE THREAD

**Issue by guiaparicio** [jaywcjlove/hotkeys-js#88]
Hi guys, is possible use hotkeys with f11?

**Comment by jaywcjlove** [comment]
@guiaparicio I am not sure, you can test it.

**Comment by guiaparicio** [comment]
hotkeys('f11', function(event, handler) {
    event.preventDefault();
    alert('you pressed F11!');
});

Not work =( 

fullscreen browser is enable

**Comment by HexMox** [comment]
> ```js
> hotkeys('f11', function(event, handler) {
>     event.preventDefault();
>     alert('you pressed F11!');
> });
> ```
> 
> Not work =(
> 
> fullscreen browser is enable

@guiaparicio it is workable.

maybe u are using macOS, f11 is blocked by system, cc
https://social.technet.microsoft.com/Forums/windows/en-US/784b2bbe-353f-412e-ac9a-193d81f306b6/remote-desktop-for-mac-f11-key-not-working-on-macbook-pro-touchbar?forum=winRDc
